name: Build Angular Project

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  build:
    # The operating system for the job
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.15.1'

    # Step 3: Install dependencies using npm
    - name: Install Dependencies
      run: npm install

    # Step 4: Run the build script to build the Angular project
    - name: Build Angular Project
      run: npm run build --prod

    # Optional Step 5: Upload the build artifacts (optional)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Install SSH and SCP Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openssh-client sshpass

    - name: Set up SSH Agent
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > private_key.pem
        chmod 600 private_key.pem
        ssh-add private_key.pem
        
    - name: Deploy to Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/html/deployment/
