name: Build Angular Project

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  build:
    # The operating system for the job
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.15.1'

    # Step 3: Install dependencies using npm
    - name: Install Dependencies
      run: npm install

    # Step 4: Run the build script to build the Angular project
    - name: Build Angular Project
      run: npm run build --prod

    # Optional Step 5: Upload the build artifacts (optional)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Test Server
        env:
         REMOTE_PATH: /var/www/html/
        if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc')
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          cd ~/.ssh
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'echo "${{secrets.REPO_DEPLOY_KEY}}" > ~/.ssh/gh_key && chmod 600 ~/.ssh/gh_key && eval `ssh-agent -s` && ssh-add ~/.ssh/gh_key && cd ${{ env.REMOTE_PATH }} 
