name: Build and Deploy Angular Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build --prod

      - name: Verify dist directory after build
        run: ls -la dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Verify Downloaded Directory Structure
        run: ls -R /home/runner/work/angular/angular/

      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install SSH Client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-client sshpass

      - name: Start SSH Agent and Add Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      - name: Clean Up Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "rm -rf /var/www/html/aadpc"

      - name: Deploy to Test Server
      - name: Deploy to Test Server
        env:
          REMOTE_PATH: /var/www/html/
        run: |
          # Check if the dist directory is available in the downloaded path
          if [ -d "/home/runner/work/angular/angular/" ]; then
            echo "Deploying dist contents to server at ${{ secrets.SSH_HOST }}"
            sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r /home/runner/work/angular/angular/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ env.REMOTE_PATH }} && rm -rf aadpc
          else
            echo "dist directory not found!"
            exit 1
          fi
