name: Build and Deploy Angular Project

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'

      # Step 3: Install dependencies using npm
      - name: Install Dependencies
        run: npm install

      # Step 4: Run the build script to build the Angular project
      - name: Build Angular Project
        run: npm run build --prod

      # Step 5: Verify the dist directory exists after build
      - name: Verify dist directory after build
        run: ls -la dist

      # Step 6: Upload the build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Download Build Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      # Step 2: Verify the downloaded artifact directory
      - name: Verify Downloaded Directory
        run: ls -la /home/runner/work/angular/angular

      # Step 3: Install SSH Client
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      # Step 4: Deploy to Test Server
      - name: Deploy to Test Server
        env:
          REMOTE_PATH: /var/www/html/
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Check if the dist directory is available in the downloaded path
           if [ -d "/home/runner/work/angular/angular/dist" ]; then
          echo "Deploying dist contents to server at ${{ secrets.SSH_HOST }}"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r /home/runner/work/angular/angular/dist/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ env.REMOTE_PATH }}
          else
          echo "dist directory not found!"
          exit 1
          fi
